# 1

In [1]:
import numpy as np

   # 2

In [2]:
ar1 = np.zeros(10, int)

In [3]:
ar1[4]=5
print(ar1)

[0 0 0 0 5 0 0 0 0 0]


In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# 5
np.arange(0,9).reshape((3),(3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# 6
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [7]:
# 7 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# 8
np.random.random((3,3,3))

array([[[0.34453553, 0.95657168, 0.41250331],
        [0.21918767, 0.49183539, 0.8498145 ],
        [0.7331625 , 0.76718475, 0.60187597]],

       [[0.36720634, 0.76458532, 0.65587016],
        [0.68142465, 0.47741498, 0.92038861],
        [0.34557366, 0.0611992 , 0.55268451]],

       [[0.05654395, 0.18434037, 0.96428646],
        [0.36253402, 0.69551981, 0.41795525],
        [0.27347524, 0.8149388 , 0.61984554]]])

In [9]:
#9
print(np.random.random((9,9)).min())
print(np.random.random((9,9)).max())

2.6224250319728526e-05
0.9945128331438793


In [10]:
#10 
np.random.random((10)).mean()

0.530694601486581

In [11]:
#11
np.diag((1,2,3,4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [12]:
#12
x = np.random.random((5,5))
(x - np.mean(x))/np.std(x)

array([[-2.04473311,  1.11770645,  0.70488052, -0.70430738, -1.07594722],
       [-0.11721305,  1.28200423,  0.26858915,  1.34562176, -0.20761582],
       [ 0.35322919, -0.40697424, -1.72065963, -0.40661475, -0.63659295],
       [ 0.02559701,  0.11994988, -1.99268462,  1.54677694,  1.01216605],
       [ 1.02537367, -0.06426529,  0.26551755, -0.69266235,  1.00285799]])

In [19]:
#13
x = np.random.randint(1, 6, size=10)
y = np.random.randint(5,10, size=10)
print(x, y )
np.intersect1d(x,y)

[5 1 3 3 1 2 3 4 3 5] [8 9 6 6 7 9 5 6 7 9]


array([5])

In [28]:
#14
x = np.random.randint(0,10, size=10)
x.sort()
x

array([1, 2, 2, 4, 4, 4, 4, 6, 6, 6])

In [43]:
#15
a = np.random.randint(0,10,size=10)
print(a)
a[np.argmax(a)]=0
print(a)

[3 3 9 1 3 3 0 2 0 6]
[3 3 0 1 3 3 0 2 0 6]


In [51]:
#16
b = np.random.randint(1,3, size=9).reshape((3),(3))
print(b)


[[2 2 2]
 [2 1 2]
 [2 1 2]]


In [55]:
c = np.mean(b, axis=1, keepdims=0)
print(c)

[2.         1.66666667 1.66666667]


In [54]:
b - c

array([[ 0.        ,  0.33333333,  0.33333333],
       [ 0.        , -0.66666667,  0.33333333],
       [ 0.        , -0.66666667,  0.33333333]])

In [90]:
#17 
Z = np.arange(100)
np.random.shuffle(Z)

n=1
np.argpartition(Z[np.argsort(Z)], ( n, 99))




array([ 0,  1,  3,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       52, 51, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 77, 76, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 89, 88, 90, 91, 92, 93, 95, 94, 96, 97, 98, 99],
      dtype=int64)

In [101]:
#18

a = np.random.randint(0,8, (5,3))
print(a, '\n\n', np.where(a > 4, a**2, a))

[[7 4 6]
 [2 4 0]
 [5 3 7]
 [0 5 1]
 [6 4 0]] 

 [[49  4 36]
 [ 2  4  0]
 [25  3 49]
 [ 0 25  1]
 [36  4  0]]
