# 1

In [2]:
import numpy as np

   # 2

In [3]:
ar1 = np.zeros(10, int)

In [4]:
ar1[4]=5
print(ar1)

[0 0 0 0 5 0 0 0 0 0]


In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# 5
np.arange(0,9).reshape((3),(3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# 6
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [8]:
# 7 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# 8
np.random.random((3,3,3))

array([[[0.15926112, 0.68144434, 0.1510208 ],
        [0.05422096, 0.28848547, 0.66298131],
        [0.35465626, 0.78263441, 0.63549739]],

       [[0.77933098, 0.6662842 , 0.16989468],
        [0.02686486, 0.04361537, 0.1300261 ],
        [0.72926235, 0.43884962, 0.54215947]],

       [[0.46301673, 0.06025158, 0.18067288],
        [0.58006855, 0.49650565, 0.16160504],
        [0.90297762, 0.20314317, 0.10351423]]])

In [10]:
#9
print(np.random.random((9,9)).min())
print(np.random.random((9,9)).max())

0.0006126474811660731
0.9845116618674058


In [11]:
#10 
np.random.random((10)).mean()

0.5619353062991184

In [12]:
#11
np.diag((1,2,3,4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [13]:
#12
x = np.random.random((5,5))
(x - np.mean(x))/np.std(x)

array([[-1.14385867, -0.93029791,  0.52638142,  0.1615736 ,  0.98378545],
       [ 1.46902466, -0.66732212, -0.93271473, -0.06348253,  1.15002139],
       [ 1.77950533,  1.80267276, -0.8147139 , -0.84818477, -1.22731371],
       [-0.90278738, -0.75122866,  0.15025996,  0.3780478 , -0.2667564 ],
       [-0.97843209,  0.72071856,  1.80843382, -0.92704326, -0.47628863]])

In [14]:
#13
x = np.random.randint(1, 6, size=10)
y = np.random.randint(5,10, size=10)
print(x, y )
np.intersect1d(x,y)

[2 1 3 1 4 3 2 1 5 5] [9 8 5 9 6 6 8 6 6 5]


array([5])

In [15]:
#14
x = np.random.randint(0,10, size=10)
x.sort()
x

array([0, 1, 1, 2, 2, 5, 6, 6, 7, 9])

In [16]:
#15
a = np.random.randint(0,10,size=10)
print(a)
a[np.argmax(a)]=0
print(a)

[8 8 9 8 6 9 6 1 4 0]
[8 8 0 8 6 9 6 1 4 0]


In [17]:
#16
b = np.random.randint(1,3, size=9).reshape((3),(3))
print(b)


[[2 1 1]
 [2 2 2]
 [1 2 1]]


In [18]:
c = np.mean(b, axis=1, keepdims=0)
print(c)

[1.33333333 2.         1.33333333]


In [19]:
b - c

array([[ 0.66666667, -1.        , -0.33333333],
       [ 0.66666667,  0.        ,  0.66666667],
       [-0.33333333,  0.        , -0.33333333]])

In [20]:
#17 
Z = np.arange(100)
np.random.shuffle(Z)

n=5
np.argpartition(Z[np.argsort(Z)], ( n, 99))




array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       50, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 76, 75, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 89, 88, 90, 91, 92, 93, 95, 94, 96, 97, 98, 99],
      dtype=int64)

In [21]:
#18

a = np.random.randint(0,8, (5,3))
print(a, '\n\n', np.where(a > 4, a**2, a))

[[1 5 5]
 [3 5 0]
 [0 2 7]
 [7 5 3]
 [7 1 5]] 

 [[ 1 25 25]
 [ 3 25  0]
 [ 0  2 49]
 [49 25  3]
 [49  1 25]]
